version: "3.7"

services:
  app:
    build: ui
    command: ["npx", "serve", "build"]
    user: dockeruser
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - backend
  backend:
    build: backend
    command: ["node", "dist/server.js"]
