version: "3.7"

services:
  app:
    build: ui
    user: dockeruser
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - backend1
  backend1:
    build: backend
    ports:
      - "8000:8000"
